version: 2
jobs:
    build-and-test:
        macos:
            xcode: "9.2.0"

        steps:
            - checkout
            - run:
                name: Retrieve Attest Framework
                command: sh ./Scripts/CurlFramework.sh

            - run:
                name: Open Accessibility Inspector
                command: open /Applications/Xcode.app/Contents/Applications/Accessibility\ Inspector.app/

            - run:
                name: Build and Run Tests
                command: fastlane scan
                environment:
                    SCAN_DEVICE: iPhone X
                    SCAN_SCHEME: AttestiOSApp

            - run:
                name: Test Free Version of Framework Access
                command: |
                    curl -s -H "X-JFrog-Art-Api: ${DEQUE_FREE_APIKEY}" -O "https://agora.dequecloud.com/artifactory/AttestIOSFree/framework/Xcode9.2/Attest.framework-${DEQUE_ATTEST_IOS_VERSION}.zip"
                    unzip Attest.framework-${DEQUE_ATTEST_IOS_VERSION}.zip

            - store_test_results:
                path: reports/report.xml

workflows:
    version: 2
    build-and-test:
        jobs:
            - build-and-test
