version: 2
jobs:
    build-and-test:
        macos:
            xcode: "9.1.0"

        steps:
            - checkout
            - run:
                name: Retrieve Attest Framework
                command: sh ./Scripts/CurlFramework.sh

            - run:
                name: Open Accessibility Inspector
                command: open /Applications/Xcode.app/Contents/Applications/Accessibility\ Inspector.app/

            - run:
                name: Build and Run Tests
                command: fastlane scan
                environment:
                    SCAN_DEVICE: iPhone X
                    SCAN_SCHEME: AttestiOSApp

            - store_test_results:
                path: reports/report.xml

workflows:
    version: 2
    build-and-test:
        jobs:
            - build-and-test
